# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

[tools]
"cargo:bacon" = "3.7.0"
"cargo:cargo-about" = "0.6.6"
"cargo:cargo-audit" = "0.21.0"
"cargo:cargo-llvm-cov" = "0.6.16"
"cargo:cargo-nextest" = "0.9.87"
"cargo:cargo-toml-lint" = "0.1.1"
"cargo:cross" = "0.2.5"
"cargo:mdbook" = "0.4.43"
"cargo:mdbook-inline-highlighting" = "0.1.0"
"cargo:mdbook-plantuml" = "0.8.0"
"cargo:semantic-release-cargo" = "2.4.0"
node = "22.14.0"
"npm:conventional-changelog-conventionalcommits" = "8.0.0"
"npm:semantic-release" = "24.2.1"
"npm:semantic-release-export-data" = "1.1.0"
"npm:vercel" = "latest"
"pipx:pre-commit" = "4.0.1"
