---
branches:
    - v[0-9]+.[0-9]+.[0-9]+
    - main
    - name: next
      prerelease: true
plugins:
    - '@semantic-release/commit-analyzer'
    - - '@semantic-release/changelog'
      - changelogFile: CHANGELOG.md
    - - '@semantic-release/release-notes-generator'
      - preset: conventionalcommits
    - - '@semantic-release/github'
      - assets:
            - path: dist/aarch64-apple-darwin/tactix-aarch64-apple-darwin
              label: tactix-aarch64-apple-darwin
            - path: dist/aarch64-apple-darwin/tactix-bench-aarch64-apple-darwin
              label: tactix-bench-aarch64-apple-darwin
            - path: dist/aarch64-unknown-linux-gnu/tactix-aarch64-unknown-linux-gnu
              label: tactix-aarch64-unknown-linux-gnu
            - path: dist/aarch64-unknown-linux-gnu/tactix-bench-aarch64-unknown-linux-gnu
              label: tactix-bench-aarch64-unknown-linux-gnu
            - path: dist/aarch64-unknown-linux-musl/tactix-aarch64-unknown-linux-musl
              label: tactix-aarch64-unknown-linux-musl
            - path: dist/aarch64-unknown-linux-musl/tactix-bench-aarch64-unknown-linux-musl
              label: tactix-bench-aarch64-unknown-linux-musl
            - path: dist/i686-unknown-linux-gnu/tactix-i686-unknown-linux-gnu
              label: tactix-i686-unknown-linux-gnu
            - path: dist/i686-unknown-linux-gnu/tactix-bench-i686-unknown-linux-gnu
              label: tactix-bench-i686-unknown-linux-gnu
            - path: dist/i686-unknown-linux-musl/tactix-i686-unknown-linux-musl
              label: tactix-i686-unknown-linux-musl
            - path: dist/i686-unknown-linux-musl/tactix-bench-i686-unknown-linux-musl
              label: tactix-bench-i686-unknown-linux-musl
            - path: dist/x86_64-apple-darwin/tactix-x86_64-apple-darwin
              label: tactix-x86_64-apple-darwin
            - path: dist/x86_64-apple-darwin/tactix-bench-x86_64-apple-darwin
              label: tactix-bench-x86_64-apple-darwin
            - path: dist/x86_64-unknown-linux-gnu/tactix-x86_64-unknown-linux-gnu
              label: tactix-x86_64-unknown-linux-gnu
            - path: dist/x86_64-unknown-linux-gnu/tactix-bench-x86_64-unknown-linux-gnu
              label: tactix-bench-x86_64-unknown-linux-gnu
            - path: dist/x86_64-unknown-linux-musl/tactix-x86_64-unknown-linux-musl
              label: tactix-x86_64-unknown-linux-musl
            - path: dist/x86_64-unknown-linux-musl/tactix-bench-x86_64-unknown-linux-musl
              label: tactix-bench-x86_64-unknown-linux-musl
            - path: dist/x86_64-pc-windows-gnu/tactix-x86_64-pc-windows-gnu
              label: tactix-x86_64-pc-windows-gnu
            - path: dist/x86_64-pc-windows-gnu/tactix-bench-x86_64-pc-windows-gnu
              label: tactix-bench-x86_64-pc-windows-gnu
            - path: dist/i686-pc-windows-gnu/tactix-i686-pc-windows-gnu
              label: tactix-i686-pc-windows-gnu
            - path: dist/i686-pc-windows-gnu/tactix-bench-i686-pc-windows-gnu
              label: tactix-bench-i686-pc-windows-gnu
            - path: dist/SHA256SUMS
              label: SHA256SUMS
    - - '@semantic-release/exec'
      - verifyConditionsCmd: ~/.cargo/bin/semantic-release-cargo -v verify-conditions
        prepareCmd: ~/.cargo/bin/semantic-release-cargo -v prepare ${nextRelease.version}
        publishCmd: ~/.cargo/bin/semantic-release-cargo -v publish
    - - '@semantic-release/git'
      - assets:
            - Cargo.toml
            - Cargo.lock
            - CHANGELOG.md
        message: 'chore(release): ${nextRelease.version} [skip ci]'
