[package]
name = "repeated-prisoners-dilemma"
version = "1.0.0-alpha.1"
edition = "2021"
readme = "README.md"
description = ""
rust-version = "1.64.0"
repository = "https://github.com/AliSajid/repeated-prisoners-dilemma"
license = "MIT OR Apache-2.0"

[lib]
name = "repeated_prisoners_dilemma_lib"
path = "src/repeated_prisoners_dilemma_lib/lib.rs"
crate-type = ["lib"]

[[bin]]
name = "repeated-prisoners-dilemma"
path = "src/repeated_prisoners_dilemma/main.rs"

[dependencies]
clap = { version = "4.3.0", features = ["cargo", "debug", "env", "string", "unicode", "derive"] }
rand = { version = "0.8.5", features = ["log", "serde1"] }
tokio = { version = "1.28.1", features = ["full"] }


[profile.dev]
opt-level = 1
debug = true

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
