# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

[tools]
"cargo:bacon" = "3.7.0"
"cargo:cargo-about" = "0.6.6"
"cargo:cargo-nextest" = "0.9.87"
"cargo:cargo-toml-lint" = "0.1.1"
"cargo:mdbook" = "0.4.43"
"cargo:mdbook-inline-highlighting" = "0.1.0"
"cargo:mdbook-plantuml" = "0.8.0"
"pipx:pre-commit" = "4.0.1"

[tasks.clean]
description = "Clean the stale artifacts from the directory"
run = "cargo clean"

[tasks.test]
description = "Run all the tests"
run = "cargo nextest run"
depends = ["clean", "build"]

[tasks.build]
description = "Build the debug version"
run = "cargo build"


[tasks."utils:generate-about"]
description = "Generate the cargo-about files"
run = [
    "./scripts/generate_about_json.sh",
    "./scripts/generate_about_md.sh ./meta/licenses.hbs",
]

[tasks."utils:fix-lockfile"]
description = "Rebuild the Cargo.lock file after fixing conflicts"
run = ["rm Cargo.lock", "cargo update"]
