# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

[book]
authors = ["Ali Sajid Imami"]
language = "en"
multilingual = false
src = "src"
title = "The Dilemma-Tactix Book"

[rust]
edition = "2021"

[preprocessor.plantuml]
plantuml-cmd="http://www.plantuml.com/plantuml"

[preprocessor.inline-highlighting]

[output.html]
git-repository-url = "https://github.com/AliSajid/brainfoamkit"

[output.html.print]
enable = true
page-break = true
