# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Security Audit

on:
    schedule:
        - cron: 0 0 1,15 * *
    push:
        paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
    workflow_dispatch:

jobs:
    security_audit:
        if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Install mise-en-place
              uses: jdx/mise-action@v2
              env:
                MISE_ENV: audit
              with:
                experimental: true

            - name: Install Rust
              uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203
              with:
                toolchain: stable

            - name: Security Audit
              run: cargo audit
