# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Security Audit

on:
    schedule:
        - cron: 0 0 1,15 * *
    push:
        paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
    workflow_dispatch:

env:
  MISE_ENV: audit

jobs:
    security_audit:
        if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
        runs-on: ubuntu-24.04
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
            with:
              disable-sudo: true
              egress-policy: audit
              allowed-endpoints: >
                api.deps.dev:443
                api.github.com:443
                api.securityscorecards.dev:443
                github.com:443
                mise.jdx.dev
                objects.githubusercontent.com
          - name: Checkout
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

          - name: Install mise-en-place
            uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2
            with:
              install: false
              experimental: true

          - name: Install Rust
            uses: dtolnay/rust-toolchain@c5a29ddb4d9d194e7c84ec8c3fba61b1c31fee8c
            with:
              toolchain: stable

          - name: Install mise tools
            env:
              MISE_ENV: audit
            run: mise install

          - name: Security Audit
            run: mise run audit
