# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Security Audit

on:
    schedule:
        - cron: 0 0 1,15 * *
    push:
        paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
    workflow_dispatch:

jobs:
    security_audit:
        if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
        runs-on: ubuntu-24.04
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
            with:
              disable-sudo: true
              egress-policy: block
              allowed-endpoints: >
                api.deps.dev:443
                api.github.com:443
                api.securityscorecards.dev:443
                github.com:443
          - name: Checkout
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Install mise-en-place
              uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2
              with:
                experimental: true

            - name: Install Rust
              uses: dtolnay/rust-toolchain@c5a29ddb4d9d194e7c84ec8c3fba61b1c31fee8c
              with:
                toolchain: stable

          - name: Security Audit
            run: cargo audit
