# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Code Coverage
on:
    workflow_call:

jobs:
    test:
        name: Generate Coverage
        runs-on: ubuntu-24.04
        container:
            image: xd009642/tarpaulin:develop-nightly@sha256:99ac7c56702187224a5d9bd30c56c010840b1007e9661216b17ebad449205661
            options: --security-opt seccomp=unconfined

        steps:
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            - uses: dtolnay/rust-toolchain@nightly
              with:
                experimental: true

            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@c5a29ddb4d9d194e7c84ec8c3fba61b1c31fee8c
              with:
                toolchain: nightly
                components: llvm-tools-preview

            - name: Collect coverage data (including doctests)
              run: |
                cargo llvm-cov --no-report nextest --config-file nextest.toml
                cargo llvm-cov --no-report --doc
                cargo llvm-cov report --doctests --lcov --output-path lcov.info

            - name: Upload to codecov.io
              uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3 # v5
              with:
                file: lcov.info
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
