# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Code Coverage
on:
    workflow_call:

jobs:
    test:
        name: Generate Coverage
        runs-on: ubuntu-24.04
        container:
            image: xd009642/tarpaulin:develop-nightly
            options: --security-opt seccomp=unconfined

        steps:
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            - name: Install mise-en-place
              uses: jdx/mise-action@v2
              with:
                version: latest
                experimental: true

            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203
              with:
                toolchain: nightly
                components: llvm-tools-preview

            - name: Collect coverage data (including doctests)
              run: |
                cargo llvm-cov --no-report nextest --config-file nextest.toml
                cargo llvm-cov --no-report --doc
                cargo llvm-cov report --doctests --lcov --output-path lcov.info

            - name: Upload to codecov.io
              uses: codecov/codecov-action@v5
              with:
                file: lcov.info
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
