# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Next semantic-release version
on:
  workflow_call:
    outputs:
      new-release-published:
        description: Indicates whether a new release will be published. The value is a string, either 'true' or 'false'.
        value: ${{ jobs.get-next-version.outputs.new-release-published }}

permissions:
  contents: read

jobs:
  get-next-version:
    name: Get next release version
    runs-on: ubuntu-24.04
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install mise-en-place
        uses: jdx/mise-action@v2
        env:
          MISE_ENV: release
        with:
          experimental: true

      - name: Get next release version
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{secrets.ACTIONS_PAT_GITHUB}}
        run: mise run get-next-version
