# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Next semantic-release version
on:
  workflow_call:
    outputs:
      new-release-published:
        description: Indicates whether a new release will be published. The value is a string, either 'true' or 'false'.
        value: ${{ jobs.get-next-version.outputs.new-release-published }}

permissions:
  contents: read

jobs:
  get-next-version:
    name: Get next release version
    runs-on: ubuntu-24.04
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install mise-en-place
        uses: jdx/mise-action@v2
      - name: Configure Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: lts/*

      - name: Cache action npm dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        id: cache-node-modules
        with:
          path: ${{ runner.temp }}/.semantic-release-action_next-release-version/node_modules
          key: |
            semantic-release-action/next-release-version-${{ runner.os }}-node-${{ hashFiles('${{ github.action_path }}/package-lock.json') }}

      - name: Install dependencies on cache miss
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm install -g semantic-release semantic-release-export-data
        shell: bash

      - name: Get next release version
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{secrets.ACTIONS_PAT_GITHUB}}
        run: mise run get-next-version
