# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Next semantic-release version
on:
  workflow_call:
    outputs:
      new-release-published:
        description: Indicates whether a new release will be published. The value is a string, either 'true' or 'false'.
        value: ${{ jobs.get-next-version.outputs.new-release-published }}

permissions:
  contents: read

jobs:
  get-next-version:
    name: Get next release version
    runs-on: ubuntu-24.04
    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install mise-en-place
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2
      - name: Configure Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          experimental: true

      - name: Get next release version
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{secrets.ACTIONS_PAT_GITHUB}}
        run: mise run get-next-version
